services:
  mongodb:
    image: mongo
    container_name: escapes_mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=siddharth
      - MONGO_INITDB_ROOT_PASSWORD=siddharth

  mongo-express:
    image: mongo-express
    container_name: escapes_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=siddharth
      - ME_CONFIG_MONGODB_ADMINPASSWORD=siddharth
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: